# Generated by Django 5.0.3 on 2024-03-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="customer",
            field=models.ManyToManyField(
                related_name="customer", to="demoapp.customer"
            ),
        ),
    ]
