# Generated by Django 5.0.3 on 2024-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0002_alter_policy_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="customer",
            field=models.ManyToManyField(to="demoapp.customer"),
        ),
    ]
