government_policies = [
("Atmanirbhar Bharat Abhiyan", "Atmanirbhar Bharat Abhiyan"),
("Mission Karmayogi", "Mission Karmayogi"),
("Pradhan Mantri SVANidhi Scheme", "Pradhan Mantri SVANidhi Scheme"),
("Samarth Scheme", "Samarth Scheme"),
("Savya Shiksha Abhiyaan", "Savya Shiksha Abhiyaan"),
("Rashtriya Gokul Mission", "Rashtriya Gokul Mission"),
("Production Linked Incentive (PLI), Scheme", "Production Linked Incentive (PLI), Scheme"),
("PM FME", "PM FME"),
("Kapila Kalam Program", "Kapila Kalam Program"),
("Pradhan Mantri Matsya Sampada Yojana", "Pradhan Mantri Matsya Sampada Yojana"),
("National Digital Health Mission", "National Digital Health Mission"),
("Solar Charkha Mission", "Solar Charkha Mission"),
("SVAMITVA Scheme", "SVAMITVA Scheme"),
("Samarth Scheme", "Samarth Scheme"),
("Sahakar Pragya Initiative", "Sahakar Pragya Initiative"),
("Housing for All Scheme", "Housing for All Scheme"),
("Sovereign Gold Bond Scheme", "Sovereign Gold Bond Scheme"),
("Fame India Scheme", "Fame India Scheme"),
("KUSUM Scheme", "KUSUM Scheme"),
("Nai Roshni Scheme", "Nai Roshni Scheme"),
("Swadesh Darshan Scheme", "Swadesh Darshan Scheme"),
("National Water Mission", "National Water Mission"),
("National Nutrition Mission", "National Nutrition Mission"),
("Operation Greens Scheme", "Operation Greens Scheme"),
("Deep Ocean Mission", "Deep Ocean Mission"),
("PM-KISAN (Pradhan Mantri Kisan Samman Nidhi), Scheme", "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi), Scheme"),
("Pradhan Mantri Kisan Maan Dhan Yojana", "Pradhan Mantri Kisan Maan Dhan Yojana"),
("PM Garib Kalyan Yojana (PMGKY)", "PM Garib Kalyan Yojana (PMGKY)"),
("Pradhan Mantri Shram Yogi Maan-Dhan", "Pradhan Mantri Shram Yogi Maan-Dhan"),
("New Jal Shakti Ministry", "New Jal Shakti Ministry"),
("Jan Dhan Yojana", "Jan Dhan Yojana"),
("Skill India Mission", "Skill India Mission"),
]